mod app;
mod bottom_pane_widget;
mod chat_widget;
mod color;
mod input_widget;
mod json_inspector;
mod logo;
mod markdown_parse;
mod shadow_render;
mod status_widget;
mod tui_models;

pub use app::run;
pub use bottom_pane_widget::render_bottom_pane;
pub use chat_widget::ensure_memory_cursor_visible;
pub use chat_widget::flush_chat_transcript;
pub use chat_widget::persist_chat_scrollback;
pub use chat_widget::render_chat;
pub use color::bright;
pub use color::bright_bold;
pub use color::default;
pub use color::default_item_style;
pub use color::dim;
pub use color::error_style;
pub use color::sentinel_assistant_styles;
pub use color::sentinel_user_styles;
pub use color::sentinel_user_bg_styles;
pub use color::hex_color;
pub use color::muted;
pub use color::selected_item_style;
pub use color::very_dim;
pub use input_widget::composer_height;
pub use input_widget::render_input;
pub use json_inspector::tree_cursor_screen_row;
pub use json_inspector::tree_render_height;
pub use json_inspector::tree_to_lines;
pub use logo::logo_lines;
pub use markdown_parse::markdown_to_lines;
pub use shadow_render::render;
pub use status_widget::render_status_line;
pub use tui_models::PendingConfirm;
pub use tui_models::PendingConfirmAction;
pub use tui_models::SLASH_COMMANDS;
pub use tui_models::SlashCommand;
pub use tui_models::TuiAppState;
