mod app;
mod color;
mod input_widget;
mod shadow_render;
mod tui_models;
mod markdown_parse;
mod chat_widget;
mod logo;
mod bottom_pane_widget;
mod status_widget;
mod json_inspector;

pub use app::run;
pub use color::hex_color;
pub use color::default;
pub use color::dim;
pub use color::bright;
pub use color::muted;
pub use color::very_dim;
pub use color::bright_bold;
pub use input_widget::render_input;
pub use tui_models::TuiAppState;
pub use tui_models::SLASH_COMMANDS;
pub use tui_models::SlashCommand;
pub use markdown_parse::markdown_to_lines;
pub use shadow_render::render;
pub use chat_widget::render_chat;
pub use logo::logo_lines;
pub use bottom_pane_widget::render_bottom_pane;
pub use status_widget::render_status_line;
pub use status_widget::render_yolo_hint;
pub use json_inspector::MemoryTreeWidget;
pub use json_inspector::tree_render_height;